/*
  Exercise for Coding Train 5.2
  Goal - practice creating and using functions with arguments

  create a pattern generated by a function (using arguments)
  call the function multiple times
  
  Modify to use a variable for the width value as well as x and y
*/

function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(250);
  happyTree(100,100,30);
  happyTree(300,50,30);
  happyTree(350,250,30);
  happyTree(220,50,30);
  happyTree(10,300,30); 
}

function happyTree (x,y,wide) {
	fill (103,84,78);
  //create trunk of tree
  rect(x-10,y,20,100);
  noStroke();
  fill(34,139,34)
  //create each of the 3 triangles that make up the tree
  triangle(x,y-60,x+wide,y-20,x-wide,y-20);
  triangle(x,y-35,x+20+wide,y+20,x-20-wide,y+20);
  triangle(x,y,x+40+wide,y+65,x-40-wide,y+65);
}
